### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function wp_get_meta_tags()

### ISSUE THREAD

**Issue by bekopharm** [dshanske/wordpress-refback#12]
Noticed today after updating Webmentions to `5.1.2`
Refback: `2.0.1`
WordPress: `6.2.2`

There seems to be no longer a function `wp_get_meta_tags`.

```
Fatal error: Uncaught Error: Call to undefined function wp_get_meta_tags() in wp-content/plugins/refback/includes/class-refback-receiver.php:440
Stack trace:
#0 wp-includes/class-wp-hook.php(308): Refback_Receiver::default_title_filter()
#1 wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 wp-content/plugins/refback/includes/class-refback-receiver.php(216): apply_filters()
#3 wp-includes/class-wp-hook.php(308): Refback_Receiver::do_refback()
#4 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 wp-includes/plugin.php(565): WP_Hook->do_action()
#6 phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(293): do_action_ref_array()
#7 phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(262): Cron_Event_Command::run_event()
#8 [internal function]: Cron_Event_Command->run()
```

**Comment by dshanske** [comment]
I really need to rewrite refbacks.
